Update dev-deployment.yml

diff --git a/.github/workflows/dev-deployment.yml b/.github/workflows/dev-deployment.yml
--- a/.github/workflows/dev-deployment.yml
+++ b/.github/workflows/dev-deployment.yml
@@ -16,6 +16,15 @@ jobs:
           REMOTE_HOST: ${{ secrets.HOST_NAME_DEV }}
           REMOTE_USER: ${{ secrets.USERNAME_DEV }}
 
+      - name: Debug SSH Key
+        run: |
+          if [ -z "${{ secrets.EC2_SSH_KEY_DEV }}" ]; then
+            echo "SSH key is missing!"
+            exit 1
+          else
+            echo "SSH key is set."
+          fi
+
       - name: Set up SSH key
         run: |
          mkdir -p ~/.ssh
